### ISSUE TITLE
Wrong image extension

### ISSUE THREAD

**Issue by quqixun** [bupt-ai-cz/BCI#2]
I cannot open any image from dataset by double clicking unless I replace .png with .jpg.
I use Ubuntu 20.04.

**Comment by SantJay** [comment]
After our test, the application 'Image viewer' that comes with the Ubuntu desktop version can't directly open our images. Maybe you can use other image viewing software or use Windows and macOS.

**Comment by quqixun** [comment]
OK. It doesn't matter, just FYI.
